<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-RBLSI6PL" name="com.qtpselenium.facebook.pom.testcases.LoginTest" tests="3" failures="0" timestamp="13 Apr 2020 19:54:28 GMT" time="69.795" errors="1">
  <testcase name="doLogin" time="36.367" classname="com.qtpselenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="sendemail" time="1.468" classname="com.qtpselenium.facebook.pom.testcases.LoginTest">
    <error type="java.lang.RuntimeException" message="javax.mail.AuthenticationFailedException">
      <![CDATA[java.lang.RuntimeException: javax.mail.AuthenticationFailedException
at com.qtpselenium.facebook.pom.mail.SendMailSSLWithAttachment.sendEMail(SendMailSSLWithAttachment.java:136)
at com.qtpselenium.facebook.pom.testcases.LoginTest.sendemail(LoginTest.java:85)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.AuthenticationFailedException
at javax.mail.Service.connect(Service.java:306)
at javax.mail.Service.connect(Service.java:156)
at javax.mail.Service.connect(Service.java:105)
at javax.mail.Transport.send0(Transport.java:168)
at javax.mail.Transport.send(Transport.java:98)
at com.qtpselenium.facebook.pom.mail.SendMailSSLWithAttachment.sendEMail(SendMailSSLWithAttachment.java:130)
... 21 more
]]>
    </error>
  </testcase> <!-- sendemail -->
  <testcase name="doLogin" time="31.960" classname="com.qtpselenium.facebook.pom.testcases.LoginTest"/>
</testsuite> <!-- com.qtpselenium.facebook.pom.testcases.LoginTest -->
